### ISSUE TITLE
error handling is bricolage

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#8]
we write messages in a temporary file which we rewind on error output.
we should use string buffers only. can we pass a NULL as file pointer to
the ErrorHandler of strus?

**Comment by patrickfrey** [comment]
You can pass a NULL file pointer. 
Then nothing is logged.
One important thing no note here is that the error buffer defines it's context by thread-id.
In an environment with coroutines other other form of cooperative context switching, tasks may share the thread-id, when executed by the same thread. In this case you have to check the error buffer for errors and fetch them before cooperative context switching. Otherwise error messages might jump from one task to an other.

**Comment by andreasbaumann** [comment]
I was under the false impression to get more if I read the logfile, this is not the case
(looking at the implementation of ErrorBuffer).

As for parallel execution I have to make a stress test to see whether my current solution holds.

**Comment by andreasbaumann** [comment]
fixed.
